[package]
name = "carla-test-server-macros"
version = "0.1.0"
edition = "2021"
description = "Procedural macros for CARLA test server management"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }