//! Pre-generated bindings module
//!
//! This module contains bindings generated by bindgen when the `bindgen` feature is enabled.
//! When building without the bindgen feature, it uses pre-generated bindings for faster builds.

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    unused,
    improper_ctypes,
    clippy::all
)]
pub mod generated;

#[allow(unused_imports)]
pub use generated::*;
