[server]
executable_path = "/home/aeon/Downloads/Carla-0.10.0-Linux-Shipping/CarlaUnreal.sh"
port = 2000
startup_timeout_seconds = 30
shutdown_timeout_seconds = 10
quality_level = "Low"
windowed = false
additional_args = ["-nosound", "-benchmark", "-fps=20"]

[coordination]
lock_file = "/tmp/carla_test_server.lock"
timeout_seconds = 300

[logging]
log_dir = "/tmp/carla_test_logs"
capture_output = true